#!/usr/bin/env python3
"""Instant-messaging traffic for the `messaging` class (step 2.6).

Messaging is defined by its silences. Short payloads, long and irregular gaps,
and a reply that follows an incoming message closely enough to look like a
person typing. A constant-rate generator would land in the same feature region
as `web` and the classifier would never learn the difference, so the timing
model here is deliberate rather than incidental.

**What this models, and why it is more than messages and replies.** The first
version of this generator sent a message and a reply and nothing else, which
produced roughly one packet per second -- below LLD section 7.6's 20-packet
window floor, so every messaging window in the dataset was discarded and the
class contributed no training rows at all (CHANGELOG.md, "LLD section 7.6's
window floor makes PRD section 9.2's sparsest class unlearnable").

The resolution is not to send messages faster. It is that a real messaging
connection carries a great deal more than messages, all of it genuinely
messaging traffic:

* **Chat states** (XEP-0085) -- `composing` when a person starts typing,
  `active` after they send. This is the "typing..." indicator, and it means
  every message is wrapped in its own small stanzas.
* **Delivery receipts** (XEP-0184) and **read markers** (XEP-0333) -- the two
  ticks and the blue tick. Every message that arrives generates a receipt when
  it lands and a marker when it is read. These are *per message*, so a burst of
  three earns three of each.
* **Message bursts.** People do not send one message per turn. They send "hey",
  then "you there", then the actual question, each its own stanza.
* **Keepalives** (XEP-0199 pings, or a whitespace ping) -- the connection is
  long-lived and NAT bindings are not, so both ends ping.
* **Roster presence.** The connection is client-to-server, not peer-to-peer.
  It carries presence for every contact on the roster, so a contact going away
  or coming back pushes a stanza that has nothing to do with the conversation.

Every one of those is a packet a passive observer of a real tunnel would see,
so including them makes the class *more* faithful rather than merely denser.
The bursty-silence signature is preserved and in fact sharpened: the enriched
model is a tight cluster of small packets around each turn, separated by the
same long idle gaps as before.

**A turn is the unit, not a message.** Receipts are per message and replies are
per turn. Getting that wrong is not a cosmetic error: a reply per message means
a three-message burst draws three replies, each of which opens a turn of up to
three more, and the conversation grows exponentially -- measured at 28 packets
in the first ten-second window and 1565 in the ninth. `_turn_scheduled` on each
side is what holds the rate flat, and `test_messaging_peer.py` asserts it does.

Deterministic for a given seed: dataset generation must be reproducible.
"""

from __future__ import annotations

import argparse
import heapq
import random
import select
import socket
import struct
import sys
import time
from collections.abc import Callable

# --- stanza vocabulary ------------------------------------------------------
#
# The wire format is a 4-byte length and a one-byte kind, because the receiver
# has to know a *message* arrived in order to answer it with a receipt, and a
# raw byte stream cannot tell a message from a typing indicator. Length framing
# rather than a delimiter because a recv() can coalesce two stanzas that were
# sent as two segments, and a receipt fired for the wrong count would be a
# silent change to the packet rate this module exists to control.

MESSAGE = 1
COMPOSING = 2
ACTIVE = 3
RECEIPT = 4
DISPLAYED = 5
PING = 6
PONG = 7
PRESENCE = 8

_HEADER = struct.Struct("!IB")

# Payload size ranges, in bytes. The message range is unchanged from the first
# version. The rest are sized as the XMPP stanzas they stand for: a chat state
# or a receipt is a short element with a JID and an id attribute, which is tens
# of bytes rather than hundreds.
_SIZES = {
    MESSAGE: (8, 220),
    COMPOSING: (40, 90),
    ACTIVE: (40, 90),
    RECEIPT: (60, 120),
    DISPLAYED: (60, 120),
    PING: (30, 60),
    PONG: (30, 60),
    PRESENCE: (70, 160),
}

# --- timing model -----------------------------------------------------------

_TYPING_PAUSE = (0.4, 2.5)
"""How long somebody types a short message for, between `composing` and the
message itself."""

_COMPOSING_LEAD = (0.1, 0.6)
"""The moment between deciding to answer and the keyboard being touched."""

_INTRA_BURST_GAP = (0.5, 1.6)
"""Between two messages of the same burst. Shorter than a turn gap: the person
is still typing at you."""

_RECEIPT_DELAY = (0.05, 0.25)
"""A receipt is generated by software the instant a stanza lands."""

_DISPLAYED_DELAY = (0.3, 1.8)
"""A read marker waits for a person to look at the screen."""

_IDLE_GAP = (1.0, 12.0)
"""Between conversational turns. Unchanged from the first version: this is the
silence that defines the class, and shortening it to clear the window floor
would be making a target met by changing the data."""

_PING_INTERVAL = (25.0, 45.0)
"""Keepalive period. Both ends run one."""

_PRESENCE_INTERVAL = (12.0, 40.0)
"""How often some contact on the roster changes state. Server side only -- a
client does not push its roster to the server."""

_BURST_MESSAGES = (1, 3)
"""Messages per turn."""


class _Framer:
    """Reassembles length-framed stanzas from a byte stream."""

    def __init__(self) -> None:
        self._buffer = bytearray()

    def feed(self, data: bytes) -> list[int]:
        """Append *data* and return the kind of every complete stanza in it."""
        self._buffer.extend(data)
        kinds: list[int] = []
        while len(self._buffer) >= _HEADER.size:
            length, kind = _HEADER.unpack_from(self._buffer, 0)
            if len(self._buffer) < _HEADER.size + length:
                break
            del self._buffer[: _HEADER.size + length]
            kinds.append(kind)
        return kinds


class _Peer:
    """One end of the conversation, driven by a schedule of timed actions.

    Single-threaded and select-driven rather than threaded, so the order of
    sends is a function of the seeded schedule rather than of how the OS
    happened to interleave two threads. A session has to replay.

    The queue holds *actions* rather than stanza kinds so that a rescheduling
    keepalive and a deferred turn are ordinary entries rather than special
    cases hooked into the send path.
    """

    def __init__(self, sock: socket.socket, rng: random.Random, deadline: float) -> None:
        self._sock = sock
        self._rng = rng
        self._deadline = deadline
        self._framer = _Framer()
        self._queue: list[tuple[float, int, Callable[[], None]]] = []
        self._tiebreak = 0
        self.turn_scheduled = False
        """Whether a turn is already on the queue. See the module docstring:
        without this the conversation grows exponentially."""
        self.closed = False
        self.sent: list[tuple[float, int]] = []
        """Every stanza sent, as (monotonic time, kind). The rate this module
        exists to control is measured off this in the tests."""
        # Every stanza is its own segment. Real clients send one stanza per
        # write over a TLS connection that has already disabled Nagle; leaving
        # it on here would coalesce a burst into a single packet and destroy
        # the shape this module is generating.
        #
        # Guarded on the family because Nagle is a TCP algorithm: on the
        # AF_UNIX pair the tests drive this class through, IPPROTO_TCP options
        # are not merely redundant but rejected (ENOTSUP on Linux). Windows
        # emulates socketpair() over loopback TCP and accepts the call, which
        # is why an unguarded setsockopt passes locally and fails in CI.
        if self._sock.family in (socket.AF_INET, socket.AF_INET6):
            self._sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

    # -- scheduling ----------------------------------------------------------

    def at(self, when: float, action: Callable[[], None]) -> None:
        self._tiebreak += 1
        heapq.heappush(self._queue, (when, self._tiebreak, action))

    def send_at(self, when: float, kind: int) -> None:
        self.at(when, lambda: self._send(kind))

    def send_after(self, delay: float, kind: int) -> float:
        when = time.monotonic() + delay
        self.send_at(when, kind)
        return when

    def uniform(self, bounds: tuple[float, float]) -> float:
        return self._rng.uniform(*bounds)

    def randint(self, bounds: tuple[int, int]) -> int:
        return self._rng.randint(*bounds)

    def every(self, bounds: tuple[float, float], kind: int) -> None:
        """A stanza that reschedules itself for the life of the connection."""

        def fire() -> None:
            self._send(kind)
            self.at(time.monotonic() + self.uniform(bounds), fire)

        self.at(time.monotonic() + self.uniform(bounds), fire)

    # -- io ------------------------------------------------------------------

    def _send(self, kind: int) -> None:
        low, high = _SIZES[kind]
        body = bytes(self._rng.getrandbits(8) for _ in range(self._rng.randint(low, high)))
        try:
            self._sock.sendall(_HEADER.pack(len(body), kind) + body)
        except OSError:
            self.closed = True
            return
        self.sent.append((time.monotonic(), kind))

    def acknowledge(self) -> float:
        """Schedule the receipt and read marker one delivered message earns.

        Per message, not per turn: three messages arriving earn three receipts
        and three read markers, which is what a real client does. Returns when
        the read marker goes out, the earliest a reply could plausibly start.
        """
        self.send_after(self.uniform(_RECEIPT_DELAY), RECEIPT)
        return self.send_after(self.uniform(_DISPLAYED_DELAY), DISPLAYED)

    def burst(self, at: float) -> None:
        """Schedule one turn: a burst of messages, each with its chat states."""
        self.turn_scheduled = False
        cursor = at
        for _ in range(self.randint(_BURST_MESSAGES)):
            self.send_at(cursor, COMPOSING)
            cursor += self.uniform(_TYPING_PAUSE)
            self.send_at(cursor, MESSAGE)
            cursor += 0.05
            self.send_at(cursor, ACTIVE)
            cursor += self.uniform(_INTRA_BURST_GAP)

    def schedule_turn(self, at: float) -> None:
        """Open a turn at *at*, unless one is already pending.

        The guard is the whole reason this is a method: a turn scheduled per
        arriving message rather than per arriving turn compounds.
        """
        if self.turn_scheduled:
            return
        self.turn_scheduled = True
        self.at(at, lambda: self.burst(at))

    def run(self, on_receive: Callable[[_Peer, int], None]) -> None:
        """Pump the schedule and the socket until the deadline.

        Waits exactly as long as the next scheduled action, so an idle gap
        costs one select() rather than a poll loop, and an arriving stanza can
        react sooner than the next send without waiting for a fixed tick.
        """
        while not self.closed and time.monotonic() < self._deadline:
            now = time.monotonic()
            timeout = self._queue[0][0] - now if self._queue else 1.0
            timeout = max(0.0, min(timeout, self._deadline - now))
            readable, _, _ = select.select([self._sock], [], [], timeout)
            if readable:
                try:
                    data = self._sock.recv(65536)
                except OSError:
                    break
                if not data:
                    break
                for kind in self._framer.feed(data):
                    on_receive(self, kind)
            now = time.monotonic()
            while self._queue and self._queue[0][0] <= now and not self.closed:
                _, _, action = heapq.heappop(self._queue)
                action()


def serve(host: str, port: int, duration_s: float, seed: int) -> None:
    """The responding end, and the roster's presence source.

    Receipts every message it is sent and answers each *turn* with one reply
    burst; never opens a turn of its own. The asymmetry is deliberate -- two
    ends that both initiated would ratchet into a continuous exchange and lose
    the silences that define the class.
    """
    rng = random.Random(seed + 1)
    srv = socket.socket(socket.AF_INET6 if ":" in host else socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind((host, port))
    srv.listen(1)
    srv.settimeout(max(duration_s, 1.0))
    try:
        conn, _ = srv.accept()
    except TimeoutError:
        print("messaging: no client connected", file=sys.stderr)
        srv.close()
        return

    deadline = time.monotonic() + duration_s
    with conn:
        peer = _Peer(conn, rng, deadline)
        peer.every(_PING_INTERVAL, PING)
        peer.every(_PRESENCE_INTERVAL, PRESENCE)
        peer.run(_responder)
    srv.close()


def _responder(peer: _Peer, kind: int) -> None:
    if kind == MESSAGE:
        read_at = peer.acknowledge()
        peer.schedule_turn(read_at + peer.uniform(_COMPOSING_LEAD))
    elif kind == PING:
        peer.send_after(peer.uniform(_RECEIPT_DELAY), PONG)


def send(host: str, port: int, duration_s: float, seed: int) -> None:
    """The initiating end: opens each turn, then falls silent for an idle gap."""
    rng = random.Random(seed)
    sock = socket.socket(socket.AF_INET6 if ":" in host else socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(10.0)
    sock.connect((host, port))
    sock.settimeout(None)

    deadline = time.monotonic() + duration_s
    with sock:
        peer = _Peer(sock, rng, deadline)
        peer.every(_PING_INTERVAL, PING)
        peer.burst(time.monotonic() + peer.uniform(_COMPOSING_LEAD))
        peer.run(_initiator)


def _initiator(peer: _Peer, kind: int) -> None:
    if kind == MESSAGE:
        read_at = peer.acknowledge()
        # The next turn opens an idle gap after this one was read, so the
        # silence sits between turns rather than between packets.
        peer.schedule_turn(read_at + peer.uniform(_IDLE_GAP))
    elif kind == PING:
        peer.send_after(peer.uniform(_RECEIPT_DELAY), PONG)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("role", choices=("serve", "send"))
    ap.add_argument("--host", required=True)
    ap.add_argument("--port", type=int, default=5222)
    ap.add_argument("--duration", type=float, default=60.0)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    (serve if args.role == "serve" else send)(args.host, args.port, args.duration, args.seed)
    return 0


if __name__ == "__main__":
    sys.exit(main())
