// Generated by scripts/gen-types.sh. Do not edit by hand.
// Regenerate after any change to the backend's Pydantic models.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assessments/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Assessments */
        get: operations["compare_assessments_api_v1_assessments_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assessment
         * @description The full ``Assessment`` document, served as stored.
         *
         *     Returned as the raw stored mapping rather than re-serialised through the
         *     Pydantic model: the document is the immutable artefact (LLD section 4.3),
         *     and round-tripping it would let a later contract change silently rewrite
         *     an assessment that was already issued.
         */
        get: operations["get_assessment_api_v1_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_v1_assessments__assessment_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_assessments__assessment_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Captures */
        get: operations["list_captures_api_v1_captures_get"];
        put?: never;
        /**
         * Upload Capture
         * @description Stream a capture to disk, dedupe on SHA-256, and record it.
         */
        post: operations["upload_capture_api_v1_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures/{capture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capture */
        get: operations["get_capture_api_v1_captures__capture_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Capture
         * @description Remove the row and the stored PCAP. Step 6.4: no orphaned file.
         */
        delete: operations["delete_capture_api_v1_captures__capture_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures/{capture_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analysis */
        post: operations["start_analysis_api_v1_captures__capture_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus database reachability.
         *
         *     Reports ``degraded`` with a 200 rather than failing the request: a
         *     dashboard needs to be able to say "the database is unreachable" to a human,
         *     and a 503 here reads to a load balancer as "take this instance out", which
         *     is the wrong response to a database that is merely cold (Neon scales to
         *     zero).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Server-sent events for one run, in LLD section 9's wire format.
         *
         *     ``X-Accel-Buffering: no`` and ``Cache-Control: no-cache`` are both load
         *     bearing: without them a proxy in front of this endpoint will buffer the
         *     stream and the dashboard's progress bar jumps from 0 to 100 at the end,
         *     which looks exactly like a hung analysis.
         */
        get: operations["stream_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeAccepted */
        AnalyzeAccepted: {
            /**
             * Captureid
             * Format: uuid
             */
            captureId: string;
            /**
             * Runid
             * Format: uuid
             * @description Poll GET /runs/{id} or stream /runs/{id}/events
             */
            runId: string;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * AnalyzeRequest
         * @description Optional body of ``POST /captures/{id}/analyze``.
         *
         *     The body itself is optional too: a POST with none starts an analysis
         *     exactly as it always has, so no existing client changes.
         */
        AnalyzeRequest: {
            /**
             * Notifyemail
             * @description Email both PDF reports to this address when the run completes. Refused with a 503 when this server has no SMTP configured.
             */
            notifyEmail?: string | null;
        };
        /** AssessmentSummary */
        AssessmentSummary: {
            /**
             * Captureid
             * Format: uuid
             */
            captureId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Exposurescore */
            exposureScore: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rating */
            rating: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Scoretotal */
            scoreTotal: number;
        };
        /**
         * AttributeDiff
         * @description One parameter, side by side. Backs the step 7.12 comparison view.
         */
        AttributeDiff: {
            /** Aprovenance */
            aProvenance?: string | null;
            /** Avalue */
            aValue?: unknown | null;
            /** Bprovenance */
            bProvenance?: string | null;
            /** Bvalue */
            bValue?: unknown | null;
            /** Changed */
            changed: boolean;
            /** Field */
            field: string;
        };
        /** Body_upload_capture_api_v1_captures_post */
        Body_upload_capture_api_v1_captures_post: {
            /**
             * File
             * @description A pcap or pcapng capture
             */
            file: string;
        };
        /** CapturePage */
        CapturePage: {
            /** Items */
            items: components["schemas"]["CaptureSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * CaptureSource
         * @description Where a capture came from. LLD section 4.3, ``captures.source``.
         * @enum {string}
         */
        CaptureSource: "upload" | "live" | "testbed";
        /** CaptureSummary */
        CaptureSummary: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Durations */
            durationS?: number | null;
            /** Filename */
            filename: string;
            /** Hasike */
            hasIke?: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Packetcount */
            packetCount?: number | null;
            /** Sha256 */
            sha256: string;
            /** Sizebytes */
            sizeBytes: number;
            source: components["schemas"]["CaptureSource"];
            /** Truncated */
            truncated?: boolean | null;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            a: components["schemas"]["AssessmentSummary"];
            /** Attributediffs */
            attributeDiffs: components["schemas"]["AttributeDiff"][];
            b: components["schemas"]["AssessmentSummary"];
            /** Findingsinboth */
            findingsInBoth: string[];
            /** Findingsonlyina */
            findingsOnlyInA: string[];
            /** Findingsonlyinb */
            findingsOnlyInB: string[];
            /** Scoredelta */
            scoreDelta: number;
        };
        /**
         * FindingCategory
         * @description Scoring category a finding is charged against. PRD section 10.1.
         *
         *     Penalties are capped per category (see ``CATEGORY_CAPS``) so that three
         *     medium cryptographic findings cannot outweigh one critical key-exchange
         *     failure.
         * @enum {string}
         */
        FindingCategory: "cryptographic_strength" | "key_exchange" | "protocol_version_mode" | "key_management" | "replay_integrity" | "metadata_exposure";
        /**
         * FindingSummary
         * @description One row of ``GET /assessments/{id}/findings``.
         *
         *     Served from the ``findings`` table rather than from the document's JSON,
         *     so severity filtering and penalty ordering are real SQL (LLD section 4.1
         *     forbids filtering on a JSON column).
         */
        FindingSummary: {
            category: components["schemas"]["FindingCategory"];
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Findingkey */
            findingKey: string;
            /** Penalty */
            penalty: number;
            /** Saspi */
            saSpi?: string | null;
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "up" | "down";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * RunStage
         * @description Pipeline stage a run is currently in. LLD section 4.3,
         *     ``analysis_runs.stage``.
         *
         *     Reported over SSE so the dashboard can show progress (FR-6.1, LLD section 9).
         * @enum {string}
         */
        RunStage: "ingest" | "track_a" | "track_b" | "assess" | "report";
        /**
         * RunStatus
         * @description Analysis run lifecycle. LLD section 4.3, ``analysis_runs.status``.
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed";
        /** RunSummary */
        RunSummary: {
            /** Assessmentid */
            assessmentId?: string | null;
            /**
             * Captureid
             * Format: uuid
             */
            captureId: string;
            /** Engineversion */
            engineVersion: string;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /** Finishedat */
            finishedAt?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Policyversion */
            policyVersion: string;
            /** Progress */
            progress: number;
            stage?: components["schemas"]["RunStage"] | null;
            /** Startedat */
            startedAt?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * Severity
         * @description Finding severity. PRD section 10.2.
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "informational";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_assessments_api_v1_assessments_compare_get: {
        parameters: {
            query: {
                /** @description Baseline assessment id */
                a: string;
                /** @description Assessment to compare against it */
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_api_v1_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_v1_assessments__assessment_id__findings_get: {
        parameters: {
            query?: {
                severity?: components["schemas"]["Severity"][] | null;
                sort?: "penalty" | "severity";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_assessments__assessment_id__report_get: {
        parameters: {
            query?: {
                format?: "executive" | "technical";
                /** @description Render HTML instead of PDF */
                inline?: boolean;
            };
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_captures_api_v1_captures_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapturePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_capture_api_v1_captures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_capture_api_v1_captures_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capture_api_v1_captures__capture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_capture_api_v1_captures__capture_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_api_v1_captures__capture_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
