"""initial schema

Revision ID: 6173d44f0cce
Revises:
Create Date: 2026-09-04 12:03:44.894542

Creates the five tables of LLD section 4.3, then upgrades the JSON columns to
JSONB on PostgreSQL only.

That last step is the whole reason the models use ``sa.JSON``. LLD section 4.1
requires one model set to serve both backends, and ``JSONB`` is a type SQLite
cannot create -- so the models stay neutral and the Postgres-specific upgrade
happens here, behind a dialect guard, where SQLite simply never reaches it.
JSONB is worth having on Postgres: it stores parsed rather than re-parsing on
every read, and it is the prerequisite for any future GIN index.

Autogenerated from ``analyzer.db.models`` and then adjusted by hand, as step 1.6
anticipates. Two adjustments beyond the JSONB step:

- ``op.create_index`` rather than the ``batch_alter_table`` wrapper autogenerate
  emitted. Batch mode exists so SQLite can fake ``ALTER``; these are plain
  ``CREATE INDEX`` statements on tables created moments earlier, and the
  unwrapped form is what actually runs on both backends.
- The two DESC indexes from LLD section 4.3 keep their descending order, which
  is how the dashboard lists runs and assessments newest-first without a sort.

Both directions must succeed on PostgreSQL and SQLite; CI runs
``upgrade head`` followed by ``downgrade base`` on each.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6173d44f0cce"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


JSON_COLUMNS: Sequence[tuple[str, str]] = (
    ("captures", "ground_truth"),
    ("analysis_runs", "model_versions"),
    ("analysis_runs", "error"),
    ("assessments", "document"),
    ("findings", "detail"),
    ("security_associations", "detail"),
)
"""Every JSON column in the schema. Kept as data so the dialect-guarded loop
below cannot drift out of step with the table definitions above it."""


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "captures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "upload", "live", "testbed", name="capturesource", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("packet_count", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("has_ike", sa.Boolean(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=True),
        sa.Column("ground_truth", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_captures")),
    )
    op.create_index("ix_captures_sha256", "captures", ["sha256"], unique=True)

    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                name="runstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "ingest",
                "track_a",
                "track_b",
                "assess",
                "report",
                name="runstage",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("progress", sa.Float(), server_default="0", nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("model_versions", sa.JSON(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_analysis_runs_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    op.create_index(
        "ix_runs_capture",
        "analysis_runs",
        ["capture_id", sa.literal_column("started_at DESC")],
        unique=False,
    )

    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("score_total", sa.SmallInteger(), nullable=False),
        sa.Column("rating", sa.Text(), nullable=False),
        sa.Column("exposure_score", sa.SmallInteger(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_assessments_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_assessments_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("run_id", name=op.f("uq_assessments_run_id")),
    )
    op.create_index(
        "ix_assessments_capture",
        "assessments",
        ["capture_id", sa.literal_column("created_at DESC")],
        unique=False,
    )

    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("finding_key", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "informational",
                name="severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "cryptographic_strength",
                "key_exchange",
                "protocol_version_mode",
                "key_management",
                "replay_integrity",
                "metadata_exposure",
                name="findingcategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("penalty", sa.SmallInteger(), nullable=False),
        sa.Column("sa_spi", sa.Text(), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_findings_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index("ix_findings_assessment", "findings", ["assessment_id", "severity"])

    op.create_table(
        "security_associations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("spi_initiator", sa.Text(), nullable=False),
        sa.Column("src_addr", sa.Text(), nullable=False),
        sa.Column("dst_addr", sa.Text(), nullable=False),
        sa.Column("packet_count", sa.Integer(), nullable=False),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_security_associations_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_associations")),
    )
    op.create_index(
        "ix_security_associations_assessment", "security_associations", ["assessment_id"]
    )

    # LLD section 4.1: the models say sa.JSON so SQLite can create them. On
    # PostgreSQL, promote to JSONB now that the tables exist. SQLite never
    # reaches this branch.
    if op.get_bind().dialect.name == "postgresql":
        for table, column in JSON_COLUMNS:
            op.execute(
                f"ALTER TABLE {table} ALTER COLUMN {column} TYPE JSONB USING {column}::jsonb"
            )


def downgrade() -> None:
    """Downgrade schema.

    No JSONB-to-JSON step is needed: dropping the tables takes their column
    types with them, and a revert followed immediately by a DROP would be dead
    work. Should this migration ever be split, the revert belongs with whichever
    half keeps the tables.
    """
    op.drop_index("ix_security_associations_assessment", table_name="security_associations")
    op.drop_table("security_associations")

    op.drop_index("ix_findings_assessment", table_name="findings")
    op.drop_table("findings")

    op.drop_index("ix_assessments_capture", table_name="assessments")
    op.drop_table("assessments")

    op.drop_index("ix_runs_capture", table_name="analysis_runs")
    op.drop_table("analysis_runs")

    op.drop_index("ix_captures_sha256", table_name="captures")
    op.drop_table("captures")
