#!/usr/bin/env bash
# Generate frontend TypeScript types from the backend's OpenAPI schema.
# Implementation-plan step 6.8, LLD section 9.
#
#   ./scripts/gen-types.sh            # write frontend/src/types/generated.ts
#   ./scripts/gen-types.sh --check    # fail if the committed file is stale
#
# The --check mode is what CI runs: a Pydantic field changed without
# regenerating types must break the build, not surface as a runtime undefined
# in the browser three days later.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/frontend/src/types/generated.ts"
SCHEMA="$(mktemp -t openapi-XXXXXX.json)"
trap 'rm -f "$SCHEMA"' EXIT

cd "$ROOT/backend"
# Dump the schema without starting a server: create_app() builds the same
# router set uvicorn would serve, and a spawned server is one more thing to
# fail in CI for reasons unrelated to types.
DATABASE_URL="${DATABASE_URL:-sqlite+aiosqlite:///./data/analyzer.db}" \
  uv run python -c "
import json, sys
from analyzer.api.main import create_app
sys.stdout.write(json.dumps(create_app().openapi(), indent=2, sort_keys=True))
" > "$SCHEMA"

cd "$ROOT/frontend"
GENERATED="$(mktemp -t generated-XXXXXX.ts)"
trap 'rm -f "$SCHEMA" "$GENERATED"' EXIT

npx --yes openapi-typescript "$SCHEMA" -o "$GENERATED"

{
  echo "// Generated by scripts/gen-types.sh. Do not edit by hand."
  echo "// Regenerate after any change to the backend's Pydantic models."
  cat "$GENERATED"
} > "$GENERATED.hdr"
mv "$GENERATED.hdr" "$GENERATED"

if [ "${1:-}" = "--check" ]; then
  if [ ! -f "$OUT" ]; then
    echo "gen-types: $OUT does not exist. Run ./scripts/gen-types.sh" >&2
    exit 1
  fi
  if ! diff -q "$OUT" "$GENERATED" >/dev/null; then
    echo "gen-types: $OUT is stale. Run ./scripts/gen-types.sh and commit the result." >&2
    diff -u "$OUT" "$GENERATED" | head -40 >&2
    exit 1
  fi
  echo "gen-types: types are up to date"
  exit 0
fi

mkdir -p "$(dirname "$OUT")"
mv "$GENERATED" "$OUT"
echo "gen-types: wrote $OUT"
